### PR TITLE
Update movies.json

### PR DESCRIPTION
**Pull request by Astha167**

### CODE REVIEW

**Comment by inuad** [comment]
@Astha167 Thank you for your contribute but Could you correct the json format agian?

**Review by Astha167 — COMMENTED** [review]
please review my changes onces

**Comment by inuad** [comment]
Hi @Astha167, I think you should correct by removing comma(,) at the last line of object. Because of the error occurs as "Failed to parse JSON file". Please try again. Thank you.

**Review by Astha167 — COMMENTED** [review]
I have removed comma . Now could you please check it once?

**Comment by inuad** [comment]
@Astha167 Great, It should work now. Thank you for contributing.

**Pull request merged**
